language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
# command to run tests
script:
  - python -m pytest
  - ./build_tools/flake_diff.sh